global_options:
  dart_mappable_builder:
    runs_before:
      - retrofit_generator
    options:
      renameMethods:
        fromJson: deserialize2
        toJson: serialize2
        fromMap: fromJson2
        toMap: toJson2
